//
//  Strings.swift
//  Hapag-Lloyd
//
//  Created by Meet Vora on 2022-07-13.
//

import Foundation

struct Strings {
    static let APP_NAME = "Hapag-Lloyd"
    static let VIEW = "View"
    static let DISMISS = "Dismiss"
    static let SEARCH = "Search"
    static let EMAIL_ADDRESS = "Email address"
    static let LOGIN = "Login"
    static let PASSWORD = "Password"
    static let NEW_PASSWORD = "New Password"
    static let CONFIRM_PASSWORD = "Confirm Password"
    static let TC_PART1 = "By logging in, you agree to our "
    static let TC_PART2 = "Terms and"
    static let TC_PART3 = "Conditions of use"
    static let SIGN_UP = "Sign up"
    static let FORGOT_PASSWORD = "Forgot password"
    static let DECLINE = "Decline"
    static let ACCEPT = "Accept"
    static let PROFILE = "Profile"
    static let LEADS = "Leads"
    static let ACTIVE = "Active"
    static let EXPIRED = "Expired"
    static let INVITE = "Invite"
    static let CANCEL = "Cancel"
    static let QUOTED = "Quoted"
    static let COMPLETED = "Completed"
    static let SSCHEDULED = "Scheduled"
    static let NEW = "New"
    static let MOBILE_NUMBER = "Mobile number"
    static let MOBILE_NUMBER_UPDATE = "Please enter your Australian mobile number"
    static let MOBILE_NUMBER_HINT = "Mobile"
    static let YOUR_ADDRESS = "Your address"
    static let ADDRESS_UPDATE = "Please enter the business address"
    static let ADDRESS_UPDATE_HINT = "New Address"
    static let CHANGE_PIN = "Change PIN"
    static let PIN_UPDATE = "Change your PIN to new"
    static let CHANGE_PIN_HINT = "New PIN"
    static let UPDATE = "Update"
    static let ADDRESS = "Address"
    static let PROFILE_SETTINGS = "Profile settings"
    static let NOTIFICATIONS = "Notifications"
    static let SETTINGS = "Settings"
    static let LEGAL = "Legal"
    static let LOGOUT = "Logout"
    static let SET_PIN_TEXT = "Set up a PIN Lock"
    static let CHANGE_PIN_TEXT = "Change PIN"
    static let FACE_ID_TEXT = "Enable Face ID"
    static let SECURITY = "Security"
    static let PRIVACY_STATEMENT = "Privacy statement"
    static let T_AND_C = "Terms and conditions"
    static let NEXT = "Next"
    static let EMAIL_ADDRESS_SUBTITLE = "Please enter your email address. This will be used as your username to login to app."
    static let EMAIL_CODE = "Email code"
    static let EMAIL_CODE_SUBTITLE = "We’ve sent a verification code to your email. Please enter now."
    static let VERIFICATION_CODE = "Verification code"
    static let RESET_PASSWORD = "Reset password"
    static let SET_PASSWORD = "Set password"
    static let SET_PASSWORD_MESSAGE = "Choose a password and create an account."
    static let RESET_PASSWORD_SUCCESS = "Your password has been set to new one. Please proceed to login."
    
    static let PROCEED_TO_LOGIN = "Proceed to login"
    static let ACCOUNT_CREATED = "Account created."
    static let ACCOUNT_CREATED_MESSAGE = "Your account has been created successfully. Proceed to login."
    
    static let YOUR_NAME = "Your name"
    static let YOUR_NAME_MESSAGE = "Please enter your first and last name"
    static let FIRST_NAME = "First name"
    static let LAST_NAME = "Last name"
    static let MOBILE_NUMBER_MESSAGE = "Please enter your Australian mobile number"
    static let MOBILE = "Mobile"
    static let MOBILE_VERIFICATION_MESSSAGE = "We’ve sent a verification code to your mobile. Please enter now."
    
    static let ERROR_INVALID_EMAIL_TITLE = "Incorrect Email"
    static let ERROR_INVALID_PASSWORD_TITLE = "Incorrect Password"
    static let ERROR_INVALID_LOGIN_TITLE = "Incorrect Login"
    static let ERROR_AUTH_FAILED_TITLE = "Authentication failed"

    static let ERROR_INVALID_EMAIL = "Incorrect email, please try again!"
    static let ERROR_INVALID_PASSWORD = "Incorrect Password, please try again!"
    static let ERROR_INVALID_LOGIN = "Incorrect email or activation code, please try again!"
    static let ERROR_AUTH_FAILED = "Unable to authorize the user, please try again!"

    
    static let PUSH_NOTIFICATIONS = "Push Notifocations"
    static let SMS_NOTIFICATIONS = "SMS Notifications"
    static let EMAIL_NOTIFICATIONS = "Email Notifications"
    static let ANNOUNCEMENTS = "Announcements"
    static let EVENTS = "Events"
}
