//
//  Strings.swift
//  Hapag-Lloyd
//
//  Created by Meet Vora on 2022-07-13.
//

import Foundation

struct Strings {
    static let APP_NAME = "Hapag-Lloyd"
    static let VIEW = "View"
    static let DISMISS = "Dismiss"
    static let SEARCH = "Search"
    static let EMAIL_ADDRESS = "Email address"
    static let LOGIN = "Login"
    static let PASSWORD = "Password"
    static let NEW_PASSWORD = "New Password"
    static let CONFIRM_PASSWORD = "Confirm Password"
    static let TC_PART1 = "By logging in, you agree to our "
    static let TC_PART1_REG = "By registering, you agree to our "
    static let TC_PART2 = "Terms and"
    static let TC_PART3 = "Conditions of use"
    static let SIGN_UP = "Sign up"
    static let FORGOT_PASSWORD = "Forgot password"
    static let DECLINE = "Decline"
    static let ACCEPT = "Accept"
    static let PROFILE = "Profile"
    static let LEADS = "Leads"
    static let ACTIVE = "Active"
    static let EXPIRED = "Expired"
    static let INVITE = "Invite"
    static let CANCEL = "Cancel"
    static let QUOTED = "Quoted"
    static let COMPLETED = "Completed"
    static let SSCHEDULED = "Scheduled"
    static let NEW = "New"
    static let MOBILE_NUMBER = "Mobile number"
    static let MOBILE_NUMBER_UPDATE = "Please enter your Australian mobile number"
    static let MOBILE_NUMBER_HINT = "Mobile"
    static let YOUR_ADDRESS = "Your address"
    static let ADDRESS_UPDATE = "Please enter the business address"
    static let ADDRESS_UPDATE_HINT = "New Address"
    static let CHANGE_PIN = "Change PIN"
    static let PIN_UPDATE = "Change your PIN to new"
    static let CHANGE_PIN_HINT = "New PIN"
    static let UPDATE = "Update"
    static let ADDRESS = "Address"
    static let PROFILE_SETTINGS = "Profile settings"
    static let NOTIFICATIONS = "Notifications"
    static let SETTINGS = "Settings"
    static let LEGAL = "Legal"
    static let LOGOUT = "Logout"
    static let SET_PIN_TEXT = "Set up a PIN Lock"
    static let CHANGE_PIN_TEXT = "Change PIN"
    static let FACE_ID_TEXT = "Enable Face ID"
    static let SECURITY = "Security"
    static let PRIVACY_STATEMENT = "Privacy statement"
    static let T_AND_C = "Terms and conditions"
    static let NEXT = "Next"
    static let EMAIL_ADDRESS_SUBTITLE = "Please enter your email address. This will be used as your username to login to app."
    static let EMAIL_ADDRESS_SUBTITLE_RESET = "Please enter your registered email address to reset your password."
    
    static let EMAIL_CODE = "Email code"
    static let EMAIL_CODE_SUBTITLE = "We’ve sent a verification code to your email. Please enter now."
    static let VERIFICATION_CODE = "Verification code"
    static let RESET_PASSWORD = "Reset password"
    static let SET_PASSWORD = "Set password"
    static let SET_PASSWORD_MESSAGE = "Choose a password and create an account."
    static let RESET_PASSWORD_SUCCESS = "Your password has been set to new one. Please proceed to login."
    
    static let PROCEED_TO_LOGIN = "Proceed to login"
    static let ACCOUNT_CREATED = "Account created."
    static let ACCOUNT_CREATED_MESSAGE = "Your account has been created successfully. Proceed to login."
    static let UPDATE_SETTINGS = "Update Settings"
    static let YOUR_NAME = "Your name"
    static let YOUR_NAME_MESSAGE = "Please enter your first and last name"
    static let FIRST_NAME = "First name"
    static let LAST_NAME = "Last name"
    static let MOBILE_NUMBER_MESSAGE = "Please enter your Australian mobile number"
    static let MOBILE = "Mobile"
    static let MOBILE_VERIFICATION_MESSSAGE = "We’ve sent a verification code to your mobile. Please enter now."
    
    static let ERROR_INVALID_EMAIL_TITLE = "Incorrect Email"
    static let ERROR_INVALID_PASSWORD_TITLE = "Incorrect Password"
    static let ERROR_INVALID_LOGIN_TITLE = "Incorrect Login"
    static let ERROR_AUTH_FAILED_TITLE = "Authentication failed"

    static let ERROR_INVALID_EMAIL = "Incorrect email, please try again!"
    static let ERROR_INVALID_PASSWORD = "Incorrect Password, please try again!"
    static let ERROR_INVALID_LOGIN = "Incorrect email or activation code, please try again!"
    static let ERROR_AUTH_FAILED = "Unable to authorize the user, please try again!"

    
    static let PUSH_NOTIFICATIONS = "Push Notifocations"
    static let SMS_NOTIFICATIONS = "SMS Notifications"
    static let EMAIL_NOTIFICATIONS = "Email Notifications"
    static let ANNOUNCEMENTS = "Announcements"
    static let EVENTS = "Events"
    
    static let NO_PROFILE_PIC = "no-photo.png"
    static let IMAGE_PICKER_TITLE = "Choose mode"
    static let IMAGE_PICKER_DESCRIPTION = "Please choose your preferred mode to set your profile image"
    static let CAMERA = "Camera"
    static let DELETE_ACCOUNT = "Request for account deletion"
    static let PHOTO_LIBRARY = "Photo Library"
    static let TERMS_LINK = "https://localfox.com.au/partner/terms"
    static let PRIVACY_LINK = "https://localfox.com.au/partner/privacy"
    static let DELETE_ACCOUNT_LINK = "https://localfox.com.au/partner/accountDeletion"
    static let PRIVACY = "Privacy"
    static let SUBMIT = "Submit"
    static let CLEAR = "Clear"
    static let NOTES = "Notes"
    static let SCHEDULE = "Schedule"
    static let NO_QUOTES_MESSAGE = "There are no quotes created on this job yet. Click create quote button to create one."
    static let NO_QUOTES_TITLE = "No quotes created yet"
    static let CREATE_NEW_QUOTE = "Create a new quote"
    static let QUOTE_DETAILS = "Quote Details"
    static let CREATE_QUOTE = "Create Quote"
    static let BOOKINGS = "Bookings"
    
    
    
    
    static let NO_INVOICE_MESSAGE = "There are no invoices created on this job yet. Click the button below to create a new invoice."
    static let NO_INVOICE_TITLE = "No invoices created"
    static let CREATE_NEW_INVOICE = "Create a new invoice"
    static let INVOICE_DETAILS = "Invoice Details"
    static let CREATE_INVOICE = "Create Invoice"
    
    static let LINE_ITEMS = "Line Items"
    static let SUB_TOTAL = "Subtotal"
    static let TAX = "Tax"
    static let TOTAL = "Total"
    static let SEND_EMAIL = "Send Email"
    static let CONVERT_TO_INVOICE = "Convert to Invoice"
    static let DELETE = "Delete"
    static let VOID = "Void"
    static let DETAILS = "Details"
    static let QUOTE = "quote:"
    static let EXPIRY = "Expiry:"
    static let CUSTOMER = "Customer"
    static let CREATED = "Created"
    static let INC_GST = "Inc GST"
    static let JOB_LOCATION = "Job location"
    static let HOW_SOON = "How soon"
    static let JOB_DESCRIPTION = "Job description"
    static let ACTIVITY = "Activity"
    static let SCHEDULES = "Schedules"
    static let QUOTES = "Quotes"
    static let INVOICES = "Invoices"
    static let JOB_DETAILS = "Job Details"
    static let VIEW_QUOTE = "View quote"
    static let REF = "Ref:"
    static let PAID_ON = "Paid on:"
    static let DUE_ON = "Due on"
    static let SAVE = "Save"
    static let ADD_JOB_NOTES = "Add job notes"
    static let ADD_LINE_ITEM = "Add line item"
    static let DESCRIPTION = "Description"
    static let PRICE = "Price"
    static let TAX_TYPE = "Tax Type"
    static let TITLE =  "Title"
    static let MARK_INVOICE_AS_PAID = "Mark as invoice paid"
}

